CREATE DATABASE JDdb;

USE JDdb;

DROP TABLE CURRENT;
DROP TABLE HISTORY;
DROP TABLE IPOOR;

CREATE TABLE CURRENT(
CurrentId int(20) NOT NULL auto_increment,
CurItemId varchar(20) NOT NULL UNIQUE,
ItemName varchar(120) NOT NULL,
URL varchar(128) NOT NULL UNIQUE,
CurPrice double(10,2) NOT NULL,
UpdTimeVersion timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY  (CurrentId)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE HISTORY(
HistoryId  int(20) NOT NULL auto_increment,
HisItemId varchar(20) NOT NULL UNIQUE,
HisPrice double(10,2) NOT NULL ,
GetTimeVersion timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY  (HistoryId)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IPOOR(
IPId  int(10) NOT NULL auto_increment,
IPURL varchar(30) NOT NULL,
HTTP varchar(10) NOT NULL,
IPTimeVersion timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY  (IPId)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
